### ISSUE TITLE
Node.js gets uninstalled in Debian Buster.

### ISSUE THREAD

**Issue by gentios** [geerlingguy/ansible-role-nodejs#109]
Hi Geerlingguy,

Thank you for your amazing work and all these ansible roles. 

I am using this role to install ```Node.js >= v8.x``` in Debian Buster, however after a day when I ssh and I do ` node -v`  it returns me ```Node.js >= 10.x``` and `npm` is not there.

Somehow it gets uninstalled and I don't know why.

I am using the role very simply as in the examples:

```
 - role: geerlingguy.nodejs
         tags: [packages, nodejs]
```
And with these variables:

```
vars:
    - nodejs_version: "8.x"
    - nodejs_npm_global_packages:
      - name: pm2
```
