### ISSUE TITLE
nodejs gets upgraded if defined version is lower than OS version

### ISSUE THREAD

**Issue by damosc** [geerlingguy/ansible-role-nodejs#150]
## Steps to reproduce
- define `nodejs_version: "14.x"`
- run playbook on Debian 12 (bookworm)
- `node --version` returns something like v14.X.Y
- run `apt upgrade` on the machine
- `node --version` returns something like v18.X.Y

## Expected result
`apt upgrade` should not upgrade nodejs package, even if the defined `nodejs_version` is lower than the one that comes per default with operating system.

## Possible solution
I'm not sure how good it is, but I solved it with
```
- name: prevent nodejs package from being upgraded
  ansible.builtin.dpkg_selections:
    name: nodejs
    selection: hold
```
