### ISSUE TITLE
Need architectures config in ansible.builtin.deb822_repository

### ISSUE THREAD

**Issue by gilbert-hsu** [geerlingguy/ansible-role-nodejs#161]
after upgrade to `7.0.0`, find notice with `apt update`

```
N: Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'https://deb.nodesource.com/node_18.x nodistro InRelease' doesn't support architecture 'i386'
```
with various architectures, an architecture map would be good ?

such like

```
architecture_map:
  amd64: amd64
  x86_64: amd64
  armv7l: arm
  aarch64: arm64
  64-bit: amd64
```

and introduce `architecture_map[ansible_architecture]` as architectures config in ansible.builtin.deb822_repository

```
ansible.builtin.deb822_repository:
  name: nodesource_{{ nodejs_version }}
  uris: "https://deb.nodesource.com/node_{{ nodejs_version }}"
  types: deb
  suites: nodistro
  architectures: "{{ architecture_map[ansible_architecture] }}"
  components: main
  signed_by: "{{ node_signed_key.dest }}"
  state: present
```
