### ISSUE TITLE
Unable to access globally installed NPM module in non login session 

### ISSUE THREAD

**Issue by louim** [geerlingguy/ansible-role-nodejs#30]
With https://github.com/geerlingguy/ansible-role-nodejs/blob/master/tasks/main.yml#L20-L24 applying only to _login session_, say I Install _bower_ with `nodejs_npm_global_packages`

Trying to do 

```
- name: Install Bower dependencies
  command: bower install
  args:
    chdir: "{{ my_path }}"
```

or even

```
- name: Install Bower dependencies
  shell: bower install
  args:
    chdir: "{{ my_path }}"
```

will not work, because Ansible run those as non-login shell, never hitting the `/etc/profile.d/npm.sh`.

**Comment by AJamesPhillips** [comment]
At the playbook level (from [@bendoh's suggestion](https://github.com/ansible/ansible/issues/14655#issuecomment-243467116)) you can do something similar to:

```
---
- name: Get ansible_env.PATH
  hosts: all
  gather_facts: Yes

- hosts: web
  environment:
    PATH: "/usr/local/lib/npm/bin:{{ ansible_env.PATH }}"
```

Alternatively on each task you can add:

    environment:
      PATH: "/usr/local/lib/npm/bin:{{ (ansible_env.PATH }}"   # or       PATH: "/usr/local/lib/npm/bin:{{ (ansible_env|default({})).PATH|default('') }}" if you have set `gather_facts: No`
