### ISSUE TITLE
npm ls -g doesn't list globally installed packages when NPM_CONFIG_PREFIX is set

### ISSUE THREAD

**Issue by x-yuri** [geerlingguy/ansible-role-nodejs#40]
`playbook.yml`:

```
- hosts: all
  become: yes

  roles:
    - role: geerlingguy.nodejs
      nodejs_version: 4.x

  tasks:
    - name: Install node packages
      npm: name={{ item }} global=yes
      with_items: [bower, gulp-cli]
```

```
# set | grep NPM
NPM_CONFIG_PREFIX=/usr/local/lib/npm
# npm ls -g


# unset NPM_CONFIG_PREFIX
# npm ls -g --depth=0
/usr/lib
├── bower@1.7.9
├── gulp-cli@1.2.2
└── npm@2.15.8

```

**Comment by geerlingguy** [comment]
What's the purpose of `NPM_CONFIG_PREFIX`, and is it typical to set this env variable in a server environment where you'd be using this role? I don't remember running into this issue before, but I only do Node.js development for a few side projects, so I'm not sure if this is a very common use case.

**Comment by x-yuri** [comment]
[From what I can tell][1], it specifies where `npm` installs global packages. And to make it clear, it's not me who [sets][2] it. And actually it looks like a [bug][3] in `ansible`'s `npm` module (not propagating environment variables), but I can't tell for sure.

[1]: https://docs.npmjs.com/getting-started/fixing-npm-permissions
[2]: https://github.com/geerlingguy/ansible-role-nodejs/blob/master/templates/npm.sh.j2#L2
[3]: https://github.com/geerlingguy/ansible-role-nodejs/blob/master/tasks/main.yml#L47

**Comment by wshelley** [comment]
Ive just pulled the latest code from here and had issues finding global npm modules as root. Something subtle has changed with the role or npm version. Changing my application to run as user rather than root as its better for security anyway.

root@vagrant:/home/vagrant# npm root -g
/usr/lib/node_modules

vagrant@vagrant:~$ npm root -g
/usr/local/lib/npm/lib/node_modules

**Comment by x-yuri** [comment]
What's `NPM_CONFIG_PREFIX` for those two users?

**Comment by wshelley** [comment]
```
vagrant@vagrant:~$ echo $NPM_CONFIG_PREFIX
/usr/local/lib/npm
```

NPM_CONFIG_PREFIX is not set for root.

I got around the issue by using the ansible npm global command rather than using this role to install global packages:

BEFORE:
```
   roles:
     - role: nodejs
       nodejs_npm_global_packages:
         - name: pm2
       nodejs_version: "4.x"
       nodejs_install_npm_user: "root"

```

AFTER:
```
  tasks:
     - name: Install pm2
       npm: name=pm2 global=yes
```
