### ISSUE TITLE
Receiving error adding nodesource apt key.

### ISSUE THREAD

**Issue by CafeLungo** [geerlingguy/ansible-role-nodejs#43]
I'm receiving the following error today on Ubuntu 14.04:

> < TASK [geerlingguy.nodejs : Add Nodesource apt key.] >
> 
> fatal: [myhost]: FAILED! => {"changed": false, "failed": true, "msg": "Failed to validate the SSL certificate for deb.nodesource.com:443. Make sure your managed systems have a valid CA certificate installed. If the website serving the url uses SNI you need python >= 2.7.9 on your managed machine or you can install the `urllib3`, `pyopenssl`, `ndg-httpsclient`, and `pyasn1` python modules to perform SNI verification in python >= 2.6. You can use validate_certs=False if you do not need to confirm the servers identity but this is unsafe and not recommended. Paths checked for this platform: /etc/ssl/certs, /etc/pki/ca-trust/extracted/pem, /etc/pki/tls/certs, /usr/share/ca-certificates/cacert.org, /etc/ansible"}

I just built a few dev VMs yesterday, and didn't run into this. I checked the cert on deb.nodesource.com:443 and it appears to be valid, seems it renewed 2 days ago for another year.

Any ideas? Everything is up to date on the ansbile host, and the box is fresh. I even ensured I ran an 'apt-get dist-upgrade', but still encounter the problem after.

Also, I tried just running `curl https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -`, and it worked fine. But still fails when I run this playbook.

**Comment by danlamanna** [comment]
Also running into this issue.

The solution (it seems) is to either upgrade python to >= 2.7.9 or to `pip install urllib3[secure]`. (http://urllib3-docs.readthedocs.io/security.html#installing-urllib3-with-sni-support-and-certificates)

**Comment by danlamanna** [comment]
In a project that doesn't use this role (yet) - I worked around this by sidestepping python: https://github.com/girder/girder/pull/1561/commits/05fceeb224430695189bf765b051e40685eb0518

**Comment by CafeLungo** [comment]
@danlamanna Thanks for pointing this out! The error message does seem to indicate what it needs to work. So, for a workaround in the meantime, either solution seems reasonable to me. But hopefully wherever the issue with the ansible module is gets fixed as a more proper solution.

Running the following before this nodejs playbook does seem to fix the issue for us:

```
- name: Install Required Packages
  apt: name={{ item }} state=present
  with_items: 
    - python-pip
    - python-dev
    - libffi-dev
    - libssl-dev

- name: Install python packages
  pip: name={{ item }} state=present
  with_items:
    - urllib3
    - pyopenssl
    - ndg-httpsclient
    - pyasn1
```
