### ISSUE TITLE
Nodesource SNI causing build failure on CentOS 6.x

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/ansible-role-nodejs#46]
See error message:

```
TASK [role_under_test : Import Nodesource RPM key.] ****************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Failed to validate the SSL certificate for rpm.nodesource.com:443. Make sure your managed systems have a valid CA certificate installed. If the website serving the url uses SNI you need python >= 2.7.9 on your managed machine or you can install the `urllib3`, `pyopenssl`, `ndg-httpsclient`, and `pyasn1` python modules to perform SNI verification in python >= 2.6. You can use validate_certs=False if you do not need to confirm the servers identity but this is unsafe and not recommended. Paths checked for this platform: /etc/ssl/certs, /etc/pki/ca-trust/extracted/pem, /etc/pki/tls/certs, /usr/share/ca-certificates/cacert.org, /etc/ansible"}
```

It started failing after Nodesource moved to Cloudfront, using new SSL certs that use SNI (which isn't easily supported by the version of Python/other deps installed on CentOS 6.

For Ubuntu, I fixed by making the same change the official Nodesource Ansible role made: https://github.com/geerlingguy/ansible-role-nodejs/commit/0372961b152fe496412b75316a1a734b4771ad3e#diff-ebbe0c3ff3753db31a12af649c45a099R7 — see https://github.com/nodesource/ansible-nodejs-role/pull/34/files#diff-2444ad0870f91f17ca6c2a5e96b26823R16

For CentOS, not exactly sure what to do to get 6 up and running again.

**Comment by trevorr** [comment]
Assuming EPEL is installed for `python-pip`, installing the following will enable SNI for Python 2.6:

```
sudo yum install -y python-pip python-devel libffi-devel openssl-devel
sudo pip install urllib3 pyopenssl ndg-httpsclient pyasn1
```

Or in Ansible:

```
  tasks:
    - name: "Python 2.6 SNI support: install pip and required devel packages"
      yum: >
        pkg={{item}}
        state=installed
      with_items:
        - python-pip
        - python-devel
        - libffi-devel
        - openssl-devel
    - name: "Python 2.6 SNI support: install Python modules"
      pip: >
        name={{item}}
        state=present
      with_items:
        - urllib3
        - pyopenssl
        - ndg-httpsclient
        - pyasn1
```

Of course, it may break again eventually:

> Warning: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. A future version of cryptography will drop support for Python 2.6

😢
