### ISSUE TITLE
Make nodejs_npm_global_packages variable easier to use

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/ansible-role-nodejs#67]
Basically, see @oxyc's comment here: https://github.com/geerlingguy/ansible-role-homebrew/pull/33#issuecomment-299746827

We could allow list items to just be `string`, and that would be the default filled in for a `name` parameter if `name` isn't provided. That way if someone sets up the packages like:

```yaml
nodejs_npm_global_packages:
  # Install a specific version of a package.
  - name: jslint
    version: 0.9.3
  # Install the latest stable release of a package.
  - node-sass
```

...it would be perfectly valid!
