### ISSUE TITLE
new LTS

### ISSUE THREAD

**Issue by tychay** [geerlingguy/ansible-role-nodejs#86]
Current LTS is 8.x, not 6.x. So #58 rears its ugly head.

I have a suggestion. Add a symbol and make it the `defaults/main.yml`…

```yaml
---
# Set to the current LTS version
nodejs_lts_version: "8.x"

# Set the version of Node.js to install ("0.12", "4.x", "5.x", "6.x", "8.x", "9.x").
# Version numbers from Nodesource: https://github.com/nodesource/distributions
nodejs_version: "{{ nodejs_lts_version }}"
```

or somesuch. (Also need to update readme.)
